config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'
  get 'static_pages/about'

  get 'welcome/homepage'

  root 'welcome#homepage'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def homepage
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
l
<!DOCTYPE html>
<html>
<head>
  <title> <%= yield(:title) %> </title>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= stylesheet_link_tag    'application', media: 'all',
                             'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'toggle', :media => "all" %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>
<%= yield %>
<input type="checkbox" name="toggle" id="toggle" onclick="scrollUp();" />
<label for="toggle"></label>
<div class="container">
</div>
<div class="message">
  <div class="social">
    <ul>
      <li>
        <%= link_to root_path do %>
            <i class="fa fa-lg fa-home" >
              <div class="tooltip">Home Page</div>
            </i>
        <% end %>
      </li>
      <li>
        <%= link_to "mailto:amruthavasili@gmail.com?Subject=Hello%20from" do %>
            <i class="fa fa-lg fa-envelope"> <div class="tooltip">Email </div></i>
        <% end %>
      </li>
      <li>
        <%= link_to "http://docdro.id/0fPlc1q" do %>
            <i class="fa fa-lg fa-file-text-o"><div class="tooltip">Resume</div> </i>
        <% end %>
      </li>
      <li>
        <%= link_to "https://github.com/mantrarush" do %>
            <i class="fa fa-lg fa-github"><div class="tooltip">Github</div> </i>
        <% end %>
      </li>
      <li>
        <%= link_to "https://www.linkedin.com/in/amruthavasili" do %>
            <i class="fa fa-lg fa-linkedin"><div class="tooltip">LinkedIn</div> </i>
        <% end %>
      </li>
      <li>
        <%= link_to "https://www.facebook.com/moth.towards.light" do %>
            <i class="fa fa-lg fa-facebook"><div class="tooltip">Facebook</div> </i>
        <% end %>
      </li>
      <li>
        <%= link_to "skype:av.vasili2?call" do %>
            <i class="fa fa-lg fa-skype"><div class="tooltip">Skype</div> </i>
        <% end %>
      </li>

      <li>
        <%= link_to static_pages_about_path do %>
            <i class="fa fa-lg fa-user"> <div class="tooltip">About me</div></i>
        <% end %>
      </li>

    </ul>
  </div>
</div>

</body>

</html>

app/views/static_pages/about.html.erb
<% provide(:title, "About me") %>
<%= stylesheet_link_tag 'customabout'%>
<div class = "custom">

  <h1>About me</h1>
  <p>
    I am a University of Illinois - Urbana Champaign graduate, who majored in electrical engineering and wants to pursue a career in computer science.
    I enjoy projects that have a mix of practicality, theory and innovation.
    Click the menu button to check my profile and reach out to me!
  </p>
</div>

app/views/welcome/homepage.html.erb
<% provide(:title, "Home") %>
<%= stylesheet_link_tag 'style'%>

<div id="particles-js"></div>

<%= javascript_include_tag 'particles', 'app'%>

<%= link_to static_pages_about_path do
  image_tag("logobutton4.png", onmouseover: "this.src='#{asset_path("logobutton3.png")}'", onmouseout: "this.src='#{asset_path("logobutton4.png")}'", :class=> "logo")
end %>